Vectors Vs Tensors

Vectors

In [1]:
# Vectors Vs Tensors using numpy
import numpy as np

# vector : representing a patient [Age, Weight, HeartRate]
patient_a = np.array([45, 70, 72])
patient_b = np.array([25, 60, 85])

print (f"Patient a vector: {patient_a}")
print (f"Dimension: {patient_a.ndim}D")  # output : 1D

Patient a vector: [45 70 72]
Dimension: 1D


Tensors

In [2]:
# tensor : representing a tiny 3*3 pixel image (Gray scale)
# values ranges 0(Black) to 255(White)
tiny_image = np.array([
    [0, 255, 0],
    [255, 255, 255],
    [0, 255, 0]
])

print ("\n Image Matrix:\n", tiny_image)
print (f"Shape: {tiny_image.shape}")  # output: (3,3)


 Image Matrix:
 [[  0 255   0]
 [255 255 255]
 [  0 255   0]]
Shape: (3, 3)


Dot product

In [3]:
# which patient is more similar to "Risk profile" vector
# high numbers here might indicate high risk
risk_profile = np.array([80, 90, 100])

# calculate similarity score
score_a = np.dot(patient_a, risk_profile)
score_b = np.dot(patient_b, risk_profile)

print(f"Patient A risk score: {score_a}")
print(f"Patient B risk score: {score_b}")

# interpretation : the higher score is "closer" to the risk profile

Patient A risk score: 17100
Patient B risk score: 15900


Matrix multiplication (the Transformer)

In [5]:
# input : 2 patients (rows), 3 features (columns)
input_data = np.array([
    [45, 70, 72], # patient A
    [25, 60, 85] # patient B
])

# weight matrix : transforms 3 features --> 1 prediction (e.g., Diabetes risk)
weights = np.array([
    [0.5], # weight for age
    [0.1], # weight for weight
    [-0.2] # weight for heartrate
])

# perform the transformation
# (2*3) dot (3*1) = (2*1) result
predictions = input_data @ weights

print ("Diabetes Risk Predictions:\n", predictions)

Diabetes Risk Predictions:
 [[15.1]
 [ 1.5]]
