In [2]:
# ARRAY Vs TENSOR
import numpy as np

# create a numpy array
arr = np.array([[1,2,3], [4,5,6]])

print(arr)
print("Type:", type(arr))
print("Shape:", arr.shape)

[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)


In [3]:
# pytorch tensor
import torch

# create a tensor
tensor = torch.tensor([[1,2,3], [4,5,6]])

print(tensor)
print("Type: ", type(tensor))
print("Shape:", tensor.shape)
print("Device:", tensor.device)

tensor([[1, 2, 3],
        [4, 5, 6]])
Type:  <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
Device: cpu


In [1]:
# GPU checking
import torch
print("CUDA Available:", torch.cuda.is_available())
print("Number of GPUs:", torch.cuda.device_count())

if torch.cuda.is_available():
    print("GPU Name:", torch.cuda.get_device_name(0))

CUDA Available: True
Number of GPUs: 1
GPU Name: NVIDIA GeForce RTX 2050


In [5]:
# moving tensor from CPU --> GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor = torch.tensor([[1.0, 2.0],
                       [3.0, 4.0]])

tensor = tensor.to(device)
print("Tensor Device:", tensor.device)


Tensor Device: cuda:0


Basic tensor operations

In [6]:
# ADDITION
a= torch.tensor([1,2,3])
b= torch.tensor([4,5,6])

print(a+b)

tensor([5, 7, 9])


In [7]:
# Multiplication
print(a*b)

tensor([ 4, 10, 18])


In [8]:
# matrix multiplication
x= torch.tensor([[1,2],[3,4]])
y= torch.tensor([[5,6],[7,8]])

print(torch.matmul(x,y))

tensor([[19, 22],
        [43, 50]])


In [9]:
# reshaping
t= torch.arange(12)
print(t)

reshaped = t.view(3,4)
print(reshaped)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [10]:
# Gradients
x= torch.tensor(2.0, requires_grad= True)

y= x**2 + 3*x +1
y.backward()

print("y=", y.item())
print("dy/dx=", x.grad)

y= 11.0
dy/dx= tensor(7.)


In [13]:
import numpy as np
# Numpy to Pytorch conversion
# Numpy to Tensor
arr= np.array([1,2,3])
tensor= torch.from_numpy(arr)
print(arr)
print(tensor)

[1 2 3]
tensor([1, 2, 3])


In [15]:
# Tensor to NumPy
tensor_np = tensor.numpy()
print(tensor_np)

[1 2 3]


In [ ]:
# if tensor is on GPU --> move to CPU first
tensor.cpu().numpy()

array([1, 2, 3])